### ISSUE TITLE
引用找不到

### ISSUE THREAD

**Issue by wangshubing1** [zhisheng17/flink-learning#7]
## 问题：
我在编写KuduColumnInfo类中引用org.apache.kudu.ColumnSchema.Encoding 与org.apache.kudu.Compression时下方
```
 this.encoding = Encoding.AUTO;
 this.compression = Compression.DEFAULT;
```

找不到那两个值

**Comment by zhisheng17** [comment]
认真再看下代码

https://github.com/zhisheng17/flink-learning/blob/master/flink-learning-connectors/flink-learning-connectors-kudu/src/main/java/com/zhisheng/connectors/kudu/connector/KuduColumnInfo.java#L181

https://github.com/zhisheng17/flink-learning/blob/master/flink-learning-connectors/flink-learning-connectors-kudu/src/main/java/com/zhisheng/connectors/kudu/connector/KuduColumnInfo.java#L196
